from flask import Flask
import os
import openai
from discord.ext import commands
from discord import Intents

app = Flask(__name__)

# Load environment variables
DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Configure OpenAI
openai.api_key = OPENAI_API_KEY

# Configure Discord
intents = Intents.default()
intents.messages = True
intents.guilds = True

bot = commands.Bot(command_prefix='!', intents=intents)

@bot.event
async def on_ready():
    print('Bot is online.')

@bot.command(name='post')
async def post(ctx, *, text: str):
    try:
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[
                {
                    "role": "system",
                    "content": "I'm Penelope, a master tweet composer and psychology guru. [...] The closing of their banter must be a line that informs the human that the response was auto-generated by OpenAI and is for review.\n"
                },
                {
                    "role": "user",
                    "content": text
                }
            ],
            temperature=1,
            max_tokens=3367,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0,
        )
        reply_text = response.choices[0].message.content.strip()
        if reply_text:
            await ctx.send(reply_text)
        else:
            await ctx.send('No content generated.')
    except Exception as e:
        print(f'Error: {e}')
        await ctx.send('Something went wrong.')

if __name__ == '__main__':
    bot.run(DISCORD_TOKEN)
