import sys
import os
import openai
from flask import Flask
from discord.ext import commands
from discord import Intents
from loguru import logger
from discord_slash import SlashCommand, SlashContext

# Setup logging based on an environment variable
DEBUG_MODE = os.getenv('DEBUG_MODE', 'False').lower() in ('true', '1', 't')
log_level = "DEBUG" if DEBUG_MODE else "INFO"
logger.add(sys.stdout, level=log_level)  # Output logs to stdout

app = Flask(__name__)

# Configure Discord
intents = Intents.default()
intents.messages = True
intents.guilds = True
bot = commands.Bot(command_prefix='!', intents=intents)
slash = SlashCommand(bot, sync_commands=True) # This synchronizes slash commands with Discord.

# Load environment variables
DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Check if environment variables are loaded (at appropriate logging level)
logger.debug(f"DISCORD_TOKEN loaded: {'Yes' if DISCORD_TOKEN else 'No'}")
logger.debug(f"OPENAI_API_KEY loaded: {'Yes' if OPENAI_API_KEY else 'No'}")

# Configure OpenAI
openai.api_key = OPENAI_API_KEY

bot_health_status = {"is_healthy": False}

@bot.event
async def on_ready():
    logger.info('Bot is online.')
    global bot_health_status
    bot_health_status["is_healthy"] = True
    print('Bot is online and marked as healthy.')

@slash.slash(name="post", description="Post a message", options=[{
    "name": "message",
    "description": "Your message",
    "type": 3,
    "required": True,
}])
async def post(ctx: SlashContext, message: str):
    logger.debug(f"Received post command with text: {message}")
    try:
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[
                {
                    "role": "system",
                    "content": "I'm Penelope, a master tweet composer and psychology guru. [...] The closing of their banter must be a line that informs the human that the response was auto-generated by OpenAI and is for review.\n"
                },
                {
                    "role": "user",
                    "content": message  # Note the variable name change here from 'text' to 'message' to match the function parameter
                }
            ],
            temperature=1,
            max_tokens=3367,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0,
        )
        reply_text = response.choices[0].message.content.strip()
        logger.debug(f"OpenAI response: {reply_text}")
        if reply_text:
            # Note the change from ctx.send to ctx.respond for slash command responses
            await ctx.respond(reply_text)
        else:
            await ctx.respond('No content generated.')
    except Exception as e:
        logger.error(f'Error: {e}')
        await ctx.respond('Something went wrong.')

if __name__ == '__main__':
    bot.run(DISCORD_TOKEN)