name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Build Discord Bot with Docker Compose
      run: docker-compose build discord-bot && docker tag postengineers_discord-bot:latest acrpostengineers.azurecr.io/discord-bot:latest
    - name: Docker Login to Azure
      run: echo "${{ secrets.AZURE_CLIENT_SECRET }}" | docker login acrpostengineers.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin
    - name: Push Discord Bot Image to Azure
      run: docker push acrpostengineers.azurecr.io/discord-bot:latest
    - name: Deploy to Azure Container Instance
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      run: |
        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
        az container show --name discord-bot --resource-group rgrouppostengineers --output table || container_exists=$?
        if [ "$container_exists" -eq 0 ]; then
          az container start --name discord-bot --resource-group rgrouppostengineers
        else
          az container create --name discord-bot --resource-group rgrouppostengineers --image acrpostengineers.azurecr.io/discord-bot:latest --cpu 1 --memory 1G
        fi
